DROP TABLE IF EXISTS `latex_templates`;
DROP TABLE IF EXISTS `global_variables`;

CREATE TABLE `latex_templates` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `latex_content` MEDIUMTEXT,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `global_variables` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `key_name` VARCHAR(255) NOT NULL UNIQUE,
  `type` ENUM('text', 'textarea', 'file') NOT NULL DEFAULT 'text',
  `value` TEXT,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
